thermal_model_params:
    motor_types: ["775_pro"]
    775_pro:
        talon_names: ["test_talon"]
        efficiency_vs_rps:
            [{rps: 0.0, eff: 0.0}, {rps: 1.0, eff: 0.5}, {rps: 2.0, eff: 0.7}, {rps: 3.0, eff: 0.5}]
        air_speed_vs_rps:
            [{rps: 0.0, speed: 0.0}, {rps: 1.0, speed: 0.5}, {rps: 2.0, speed: 0.7}, {rps: 3.0, speed: 0.5}]
        properties:
            {proportion_losses_mechanical: .3, proportion_losses_electrical: .7}
        node_names: ["test_node1", "test_node2"]
        test_node1: 
            thermal_capacity: 1.
            proportion_mechanical_loss_absorb: 1.
            proportion_electrical_loss_absorb: 0.
            initial_temperature: 287.0
            emissive_connections:
                []
            conductive_connections:
                [{id: "test_node2", k: 1., area: 1., dist: 1., infinite_thermal_sink: false}]
            natural_convective_connections:
                []
            fan_convective_connections:
                []
        test_node2: 
            thermal_capacity: 1.
            proportion_mechanical_loss_absorb: 0.
            proportion_electrical_loss_absorb: 1.
            initial_temperature: 287.0
            emissive_connections:
                []
            conductive_connections:
                []
            natural_convective_connections:
                []
            fan_convective_connections:
                []
