#goal definition
bool IntakeCube
bool IntakeCubeNoLift
bool GoToHeight
bool MoveArmAway
float64 x
float64 y
bool up_or_down
bool override_pos_limits
---
#result definition
float64 data
---
#feedback
float64 data
