#!/usr/bin/env python
import sys

from rqt_driver_station_sim.driver_station_sim import DriverStationSim
from rqt_gui.main import Main

plugin = 'rqt_driver_station_sim.driver_station_sim.DriverStationSim'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=DriverStationSim.add_arguments))
