#For 2018 prac bot
swerve_drive_controller:
    steering_joint_fl: 
        offset: 2.034056807
    steering_joint_fr: 
        offset: 2.57708772364788
    steering_joint_bl: 
        offset: -0.121184482242966
    steering_joint_br: 
        offset: 2.51419
