Header header

float64  leftStickX
float64  leftStickY

float64  rightStickX
float64  rightStickY

float64  leftTrigger
float64  rightTrigger

bool buttonAButton
bool buttonAPress
bool buttonARelease

bool buttonBButton
bool buttonBPress
bool buttonBRelease

bool buttonXButton
bool buttonXPress
bool buttonXRelease

bool buttonYButton
bool buttonYPress
bool buttonYRelease

bool bumperLeftButton
bool bumperLeftPress
bool bumperLeftRelease

bool bumperRightButton
bool bumperRightPress
bool bumperRightRelease

bool buttonBackButton
bool buttonBackPress
bool buttonBackRelease

bool buttonStartButton
bool buttonStartPress
bool buttonStartRelease

bool stickLeftButton
bool stickLeftPress
bool stickLeftRelease

bool stickRightButton
bool stickRightPress
bool stickRightRelease
